[package]
name = "lowRes-tv-ascii-Render"
version = "0.1.0"
edition = "2024"

[dependencies]
pixel2ascii = "0.1.1"
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"
image = "0.25"
serde_json = "1.0"
